### ISSUE TITLE
Cookie -> Session storage: Make Regex more accommodating for setting cookie values

### ISSUE THREAD

**Issue by Jamesr51d** [51Degrees/javascript-templates#12]
# Background 

An issue has arisen where javascript property values contain Javascript that continues to add cookie values even when the pipeline parameter 'EnableCookies' is set to false. This is because when the processJsProperties function uses regex to search and replace the cookie setting javascript. If it doesn't meet a specific format then this transformation will not occur.

# Objective 

Make the regex more adaptable to different formatting options. e.g. 
single string - `document.cookie = "51D_ProtectedAudienceAPIEnabled=True";`
single quotes instead of double quotes - `document.cookie = '51D_ProtectedAudienceAPIEnabled=True';`

**Comment by justadreamer** [comment]
For now it seems best to provide a good documentation with examples that the template is able to process.   The doc was partially written as part of this PR: #11, but we'll improve with some samples, of which the above ones are negative samples that don't seem to fit, and then if it becomes absolutely needed - we'd need to make the template more robust.

**Comment by Jamesr51d** [comment]
Okay sounds good to me
________________________________

**Comment by justadreamer** [comment]
Hi @Jamesr51d, @BohdanVV has added some examples to the docs as part of the PR #11 that you've started  - could you please check them and close this issue if the docs look good to you.  Thank you.

**Comment by Jamesr51d** [comment]
Yeah that looks good to me
