### ISSUE TITLE
Complete event is not called if the /json endpoint results in an error

### ISSUE THREAD

**Issue by jwrosewell** [51Degrees/javascript-templates#7]
Issue 51Degrees/device-detection-php-onpremise#11 relates to the example not responding to the end point because the settings/configuration is not being set as expected. The impact is that the `fod.Complete` event does not fire.

However there are other reasons that would prevent the `fod.Complete` from firing. For example; the CORS configuration is not correct if the JavaScript and JSON endpoints on are different origins to the calling web page.

We need to review the error handling associated with the subsequent calls to the JSON end point and present clearer error messages.

**Comment by justadreamer** [comment]
according to @drasmart research: 

### App killed before json sent

```text
POST http://localhost:5101/51dpipeline/json net::ERR_CONNECTION_REFUSED
```

### Offline via dev tools

```text
POST http://localhost:5101/51dpipeline/json net::ERR_INTERNET_DISCONNECTED
```

### Timeout

_(There is no timeout set on XMLHttpRequest.)_

### CORS block

```text
Access to XMLHttpRequest at 'https://localhost:5001/51dpipeline/json' from origin 'http://localhost:5101' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://localhost:5301' that is not equal to the supplied origin.
```

### (Effectively) Empty JSON

```text
Uncaught TypeError: Cannot read properties of undefined (reading 'hardwarename')
    at (index):246:51
    at Array.<anonymous> (51Degrees.core.js:1:5478)
    at y (51Degrees.core.js:1:4363)
    at p (51Degrees.core.js:1:4427)
    at u.onload (51Degrees.core.js:1:4999)
```

## Suggested amendments to the error message
So in the case json was not parsable - the error should be caught and logged into the console: "/json endpoint did not return a valid JSON - please verify the setup and CORS headers for the endpoint".  the fod.complete still should be called with an empty JSON.

**Comment by drasmart** [comment]
[[XMLHttpRequest: error event](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/error_event)] does not provide enough information for our [[onerror handler](https://github.com/51Degrees/javascript-templates/blob/a0642e361691cf9368253497a850eb060a4eb010/JavaScriptResource.mustache#L464-L469)] to identify CORS errors specifically among other network related issues.

The specific errors are logged by the Chrome itself and can not be improved.

![Screenshot 2024-05-09 131452](https://github.com/51Degrees/javascript-templates/assets/5711520/7092641e-3d32-41e2-ba42-c45a4443f596)

**Comment by justadreamer** [comment]
@BohdanVV could you please verify if this one is working as expected

**Comment by BohdanVV** [comment]
I've checked the implemented solution, and it works well.

I simulated a 405 server response, the callback was triggered, and here is the data/error I received as a result:

```JSON
{
    "device": {
        ...
    },
    "javascriptProperties": [
        ...
    ],
    "errors": [
        "Invalid JSON - the endpoint is likely setup incorrectly\n--- caused by ---\nUnexpected end of JSON input"
    ]
}
```

**Comment by justadreamer** [comment]
works as expected now, is present in all onpremise implementations, needs to be released to the cloud
